export enum UBL_EXTENSION_INDEX {
  'CORRECTIVE_DATA' = 1,
  'DIFF_VALUES' = 2,
  'ADDITIONAL_CORRECTIVE_INVOICE_GROSS_DATA' = 3,
  'ADDITIONAL_ADRESS_DATA' = 4,
}

export enum UBL_EXTENSION_INDEX_SPEC {
  'ADDITIONAL_INVOICE_GROSS_DATA',
  'UTILITY_CONSUMPTION_POINTS',
  'ADDITIONAL_INVOICE_DATA_NETTO',
  'ADDITIONAL_ADRESS_DATA',
}

export enum SectionType {
  Basic,
  BeforeCorrection,
  AfterCorrection,
  Summary,
}
